### ISSUE TITLE
ValueError: split() requires a non-empty pattern match.

### ISSUE THREAD

**Issue by zhuba-Ahhh** [ChangyaoTian/VL-LTR#4]
![image](https://user-images.githubusercontent.com/84793349/170819530-357b692b-1922-468c-be54-fd3320edb9b3.png)

As shown in the figure。Can you help me？

**Comment by zhuba-Ahhh** [comment]
ValueError: split() requires a non-empty pattern match.
(VL) root@constu2:/home/data/yanwenjun/Paddle/15/VL-LTR# bash eval.sh configs/placeslt/pretrain/places_pretrain_vit16.py 1 --eval-pretrain
+ export NCCL_LL_THRESHOLD=0
+ NCCL_LL_THRESHOLD=0
+ CONFIG=configs/placeslt/pretrain/places_pretrain_vit16.py
+ GPUS=1
+ CPUS=4
+ PORT=8886
+ CONFIG_NAME=places_pretrain_vit16.py
+ CONFIG_NAME=places_pretrain_vit16
+ OUTPUT_DIR=./checkpoints/eval
+ '[' '!' -d ./checkpoints/eval ']'
+ python -u main.py --port=8886 --num_workers 4 --resume ./checkpoints/places_pretrain_vit16/checkpoint.pth --output-dir ./checkpoints/eval --config configs/placeslt/pretrain/places_pretrain_vit16.py --eval-pretrain --eval
+ tee -a ./checkpoints/eval/train.log
Not using distributed mode
Namespace(aa='rand-m9-mstd0.5-inc1', batch_size=128, clip_grad=None, clip_ms=True, cls_token_length=1, color_jitter=0.4, config='configs/placeslt/pretrain/places_pretrain_vit16.py', context_length=75, cooldown_epochs=10, cutmix=0.0, cutmix_minmax=None, data_path='/datasets01/imagenet_full_size/061417/', data_set='PLACES_LT', debug=False, decay_epochs=30, decay_rate=0.1, desc_path='data/places', device='cuda', dist_eval=False, dist_url='env://', distillation_alpha=0, distillation_beta=0.5, distillation_tau=1.0, distillation_training_mode=False, distillation_type='logits', distributed=False, drop=0.0, drop_last=True, drop_path=0.1, ensemble=False, epochs=50, eval=True, eval_pretrain=True, finetune='', fp32_resume=False, img_grad=True, inat_category='name', input_size=224, local_rank=0, loss_type='smoothCE', lr=1e-05, lr_noise=None, lr_noise_pct=0.67, lr_noise_std=1.0, min_lr=0.0, mixup=0.0, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, model='CVLP_vit16', momentum=0.9, num_workers=4, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='./checkpoints/eval', patience_epochs=10, pin_mem=True, port=8886, pretrain_cvlp=True, pretrain_cvlp_path='', pretrained=False, pretrained_clip='pretrained/ViT-B-16.pt', recount=1, remode='pixel', repeated_aug=False, reprob=0.25, resplit=False, resume='./checkpoints/places_pretrain_vit16/checkpoint.pth', sched='cosine', seed=0, select=False, sent_length=64, smoothing=0.1, start_epoch=0, teacher_model=None, teacher_path=None, test=True, test_p=False, text_lr=0, train_interpolation='bicubic', train_mode=False, two_branch=False, txt_embed_path=None, use_sqrt_freq=True, vis_backbone_path=None, warmup_epochs=5, warmup_lr=1e-06, weight_decay=0.05, weight_sample=True, world_size=1)
using clip text tokens splitted by sentence
100%|██████████| 365/365 [00:00<00:00, 6252.87it/s]
Traceback (most recent call last):
  File "main.py", line 525, in <module>
    main(args)
  File "main.py", line 245, in main
    dataset_train, args.nb_classes = build_dataset(split="train", args=args)
  File "/home/data/yanwenjun/Paddle/15/VL-LTR/datasets.py", line 36, in build_dataset
    select=args.select
  File "/home/data/yanwenjun/Paddle/15/VL-LTR/mcloader/classification.py", line 63, in __init__
    self.text_tokens = get_sentence_tokens(dataset, desc_path, context_length)
  File "/home/data/yanwenjun/Paddle/15/VL-LTR/mcloader/classification.py", line 27, in get_sentence_tokens
    texts = preprocessor.split_sent(texts)
  File "/home/data/yanwenjun/Paddle/15/VL-LTR/mcloader/preprocess.py", line 61, in split_sent
    split_text = pat.split(text)
ValueError: split() requires a non-empty pattern match.

**Comment by ChangyaoTian** [comment]
Could you provide the specific content of param `text` in `split_text = pat.split(text)` ?

**Comment by flytocc** [comment]
> Could you provide the specific content of param `text` in `split_text = pat.split(text)` ?
 
```
'a bad photo of a tench .\na photo of many tench .\na sculpture of a tench .\na photo of the hard to see tench .\na low resolution photo of the tench .\na rendering of a tench .\ngraffiti of a tench .\na bad photo of the tench .\na cropped photo of the tench .\na tattoo of a tench .\nthe embroidered tench .\na photo of a hard to see tench .\na bright photo of a tench .\na photo of a clean tench .\na photo of a dirty tench .\na dark photo of the tench .\na drawing of a tench .\na photo of my tench .\nthe plastic tench .\na photo of the cool tench .\na close-up photo of a tench .\na black and white photo of the tench .\na painting of the tench .\na painting of a tench .\na pixelated photo of the tench .\na sculpture of the tench .\na bright photo of the tench .\na cropped photo of a tench .\na plastic tench .\na photo of the dirty tench .\na jpeg corrupted photo of a tench .\na blurry photo of the tench .\na photo of the tench .\na good photo of the tench .\na rendering of the tench .\na tench  in a video game.\na photo of one tench .\na doodle of a tench .\na close-up photo of the tench .\na photo of a tench .\nthe origami tench .\nthe tench  in a video game.\na sketch of a tench .\na doodle of the tench .\na origami tench .\na low resolution photo of a tench .\nthe toy tench .\na rendition of the tench .\na photo of the clean tench .\na photo of a large tench .\na rendition of a tench .\na photo of a nice tench .\na photo of a weird tench .\na blurry photo of a tench .\na cartoon tench .\nart of a tench .\na sketch of the tench .\na embroidered tench .\na pixelated photo of a tench .\nitap of the tench .\na jpeg corrupted photo of the tench .\na good photo of a tench .\na plushie tench .\na photo of the nice tench .\na photo of the small tench .\na photo of the weird tench .\nthe cartoon tench .\nart of the tench .\na drawing of the tench .\na photo of the large tench .\na black and white photo of a tench .\nthe plushie tench .\na dark photo of a tench .\nitap of a tench .\ngraffiti of the tench .\na toy tench .\nitap of my tench .\na photo of a cool tench .\na photo of a small tench .\na tattoo of the tench .The tench or doctor fish (Tinca tinca) is a fresh- and brackish-water fish of the order Cypriniformes found throughout Eurasia from Western Europe including the British Isles east into Asia as far as the Ob and Yenisei Rivers. It is also found in Lake Baikal. It normally inhabits slow-moving freshwater habitats, particularly lakes and lowland rivers.\nThe tench was formerly classified in the subfamily Leuciscinae with other Eurasian minnows, but more recent phylogenetic studies have supported it belonging to its own family Tincidae.\nThe tench is most often found in still waters with a clay or muddy substrate and abundant vegetation. This species is rare in clear waters across stony substrate, and is absent altogether from fast-flowing streams. It tolerates water with a low oxygen concentration, being found in waters where even the carp cannot survive.\nTench feed mostly at night with a preference for animals, such as chironomids, on the bottom of eutrophic waters and snails and pea clams in well-vegetated waters.Breeding takes place in shallow water usually among aquatic plants where the sticky green eggs can be deposited. Spawning usually occurs in summer, and as many as 300,000 eggs may be produced. Growth is rapid, and fish may reach a weight of 0.11 kg (0.25 lb) within the first year.\nTench have a stocky, carp-like shape and olive-green skin, darker above and almost golden below. The tail fin is square in shape. The other fins are distinctly rounded in shape. The mouth is rather narrow and provided at each corner with a very small barbel. Maximum size is 70 cm, though most specimens are much smaller. A record fish caught in 2001 in England had a weight of 15 lb 3 oz (6.89 kg). The eyes are small and red-orange in colour. Sexual dimorphism is absent or weak, limited to the adult females having a more convex ventral profile when compared with males.Males may also possess a very thick and flattened outer ray to the ventral fins. Males are generally smaller than females, but can be recognised by having more curved lower fins and noticeable muscles around the base of the fins generally absent in female.The tench has very small scales, which are deeply embedded in a thick skin, making it as slippery as an eel. Folklore has it that this slime cured any sick fish that rubbed against it, and from this belief arose the name doctor fish.\nAn artificially bred variety of tench called the golden tench  is a popular ornamental fish for ponds. This form varies in colour from pale gold through to dark red, and some fish have black or red spots on the flanks and fins. Though somewhat similar to the goldfish, because these fish have such small scales, their quality is rather different.\nTench are edible, working well in recipes that would otherwise call for carp, but are rarely eaten these days. They are shoaling fish that are popular quarries for coarse angling in rivers, lakes and canals. Tench, particularly golden tench, are also kept as ornamental fish in ponds as they are bottom feeders that help to keep the waterways clean and healthy.\nLarge tench may be found in gravel pits or deep, slow-moving waters with a clayey or silty bottom and copious aquatic vegetation. The best methods and bait to catch tench are float fishing and ledgering with a swim feeder using maggots, sweetcorn, pellets, bread, and worms. Fish over 1 kg (2 lb) in weight are very strong fighters when caught on a rod.'
```

**Comment by rahulvigneswaran** [comment]
@ChangyaoTian @flytocc @zhuba-Ahhh  Any fixes for this?

**Comment by flytocc** [comment]
> @ChangyaoTian @flytocc @zhuba-Ahhh Any fixes for this?

caused by python version

**Comment by rahulvigneswaran** [comment]
> > @ChangyaoTian @flytocc @zhuba-Ahhh Any fixes for this?
> 
> caused by python version

Which version fixes it?

**Comment by flytocc** [comment]
maybe you can try 3.8+

**Comment by rahulvigneswaran** [comment]
@flytocc Issue still persists even after upgrading to python version 3.6.13.

**Comment by rahulvigneswaran** [comment]
> maybe you can try 3.8+

I can confirm that this fixes this issue! Thanks a lot!
